### model
model_name_or_path: /media/5/yx/model_cache/Llama-3.2-1B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: kgw_prefix_1
template: default
cutoff_len: 1024
max_samples: 1000000
# max_samples: 30000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/direct_distillation/llama3.2-1b/kgw_p_1
logging_steps: 10
save_steps: 10000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
# bf16: true
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 2000

# wandb
report_to: none   # wandb none
run_name: distill

